name: trycycler-docker
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies: 
  - bioconda::minimap2=2.17
  - bioconda::trycycler=0.4.1
  - bioconda::mash=2.2.2
  - bioconda::miniasm=0.3_r179
  - bioconda::muscle=3.8.1551
  - conda-forge::r-base=4.0.3
  - conda-forge::r-ape=5.3
  - conda-forge::r-phangorn=2.5.5

